{% set name = "langchain-huggingface" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_huggingface-{{ version }}.tar.gz
  sha256: 18a2d79955271261fb245b233fea6aa29625576e841f2b4f5bee41e51cc70949

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - huggingface_hub >=0.33.4,<1.0.0
    - python >={{ python_min }},<4.0
    - langchain-core >=1.2.0,<2.0.0
    - tokenizers >=0.19.1,<1.0.0
    - transformers >=4.39.0
    - sentence-transformers >=2.6.0
    - huggingface_hub >=0.33.4,<1.0.0

test:
  imports:
    - langchain_huggingface
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Hugging Face and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
