{% set name = "langchain-huggingface" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_huggingface-{{ version }}.tar.gz
  sha256: fa77a9545de77e7be4a7de134f692da413fc3b2b99d364fc9bcd0c6fa6fcb35c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.3.0,<0.4
    - tokenizers >=0.19.1
    - transformers >=4.39.0
    - sentence-transformers >=2.6.0
    - huggingface_hub >=0.23.0

test:
  imports:
    - langchain_huggingface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Hugging Face and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
