{% set name = "langchain-huggingface" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_huggingface-{{ version }}.tar.gz
  sha256: 0637acf484c47323cf3dcc46745a93467f6955989af9b7c01e2382fe1b630aaf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8.1,<4.0
    - langchain-core >=0.1.52,<0.3
    - tokenizers >=0.19.1
    - transformers >=4.39.0
    - sentence-transformers >=2.6.0
    - text-generation >=0.7.0,<0.8.0
    - huggingface_hub >=0.23.0

test:
  imports:
    - langchain_huggingface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Hugging Face and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
